### ISSUE TITLE
$.localStorage refers to null in IE11

### ISSUE THREAD

**Issue by hy9be** [artberri/jquery-html5storage#1]
Gets error in IE11
SCRIPT5007: Unable to get property 'getItem' of undefined or null reference

**Comment by hy9be** [comment]
Seems the error is for local files only. FYI.

**Comment by marcus-hiles** [comment]
Hi @hy9be please what do you mean by "local files only", cos I thought localStorage already dealt with local files only?

**Comment by artberri** [comment]
This is a deprecated project
